### ISSUE TITLE
Automator: foutmelding by downloaden Alternative Math

### ISSUE THREAD

**Issue by micheldebree** [micheldebree/reality#2]
Als test de video geprobeerd te downloaden die in de README genoemd staat, geeft een foutmelding:

The action “Run Shell Script” encountered an error: “mv: rename Alternative_Math_Short_Film-Zh3Yz3PiXZw.webm to /Users/michel/Downloads/Alternative_Math_Short_Film-Zh3Yz3PiXZw.webm: No such file or directory”

**Comment by mvanduijker** [comment]
Welke youtube url?
